database:
  type: 'postgres'
  host: 'postgres'
  port: 5432
  username: 'postgres'
  password: 'test'
  database: 'archon-db'

redis:
  flushAll: true
  host: 'redis'
  port: 6379

jwt: 
  nonce:
    secret: 'archon-super-secrete-jwt'
    expires: '1h'
  accessTokenExpire: '1h'
  refreshTokenExpire: '14d'

microservices:
  auth:
    url: 'http://localhost:3001'
    port: '3001'

gpg:
  baseDir: 'uploads'
  keysDir: 'keys'
  encryptedDir: 'encrypted'
  decryptedDir: 'decrypted'
  import-command: 'gpg --import '
  encrypt-command: 'gpg --trust-model always --encrypt --output '
  decrypt-command: 'gpg --trust-model always --decrypt --output '
